{% set name = "seqdat" %}
{% set version = "22.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seqdat-{{ version }}.tar.gz
  sha256: 71384c75e6315d9d0211d3eb7c79e34227edd28bba6d849a1e0c9d57143d01db

build:
  number: 0
  noarch: python
  entry_points:
    - seqdat = seqdat.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    - poetry
  run:
    - click >=8.0.3,<9.0.0
    - click-rich-help >=0.2.0
    - python >=3.6,<3.11
    - rich >=10.12.0,<11.0.0
    - ruamel.yaml >=0.17.17,<0.18.0

test:
  imports:
    - seqdat
  commands:
    - pip check
    - seqdat --help
  requires:
    - pip

about:
  home: https://github.com/daylinmorgan/seqdat
  summary: sequencing data manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
