{% set name = "seqdat" %}
{% set version = "2024.1008" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seqdat-{{ version }}.tar.gz
  sha256: f954cdd9ae66291f36770f645f1c50e35cc4adc80594a248eb09e9828b38fdcf

build:
  number: 0
  noarch: python
  entry_points:
    - seqdat = seqdat.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - pdm-backend
  run:
    - python >=3.8
    - click >=8.0.3,<9.0.0
    - click-rich-help >=0.2.0
    - rich >=10.12.0
    - tomlkit >=0.10.1

test:
  imports:
    - seqdat
  commands:
    - pip check
    - seqdat --help
  requires:
    - pip

about:
  home: https://github.com/daylinmorgan/seqdat
  summary: sequencing data manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
